### ISSUE TITLE
Disable scalastyle magic.number for `src/test` scope

### ISSUE THREAD

**Issue by Primetalk** [cotiviti/cotiviti-develtools-config#11]
It seems to be normal thing to have magic numbers in tests.

**Comment by coacoas** [comment]
The current scalastyle maven plugin configuration does not allow for a different set of rules to be run in the `testSourceDirectory`.

**Comment by coacoas** [comment]
One simple solution would be to make sure all your magic numbers are constants inside `BaseTest`, and just wrap that class with: 
```scala
// scalastyle:off magic.number
trait BaseTest extends... { 
  val timeout = 10
}
// scalastyle:on magic.number
```

**Comment by Primetalk** [comment]
We have `ScalaStyle` plugin enabled in the BigParent™. And it would be really nice if we didn't have to fix it's issues in every single test file in all our projects.
I thought @mykelalvis had an idea on how to run ScalaStyle in test scope with different configuration.

**Comment by coacoas** [comment]
If I understood it correctly, he was suggesting just not running it on tests.

**Comment by Primetalk** [comment]
https://github.com/scalastyle/scalastyle/blob/master/src/main/scala/org/scalastyle/scalariform/MagicNumberChecker.scala

It seems that it ignores `val` declarations

    val myNumber = 1234

So we may just use any numbers in tests but give them names.

**Comment by isomarcte** [comment]
@Primetalk that is the intent of the check. I support leaving this enabled and naming constants in the general case.

**Comment by coacoas** [comment]
@Primetalk @isomarcte So, can we close this issue?

**Comment by Primetalk** [comment]
@coacoas @isomarcte 
I added wiki page [https://github.com/cotiviti/cotiviti-develtools-config/wiki/Magic-number](Magic number).

**Comment by Veske** [comment]
So the official solution from the Scala community is name your magic numbers used in tests?

val sevenThousandThreeHundredTwentyOne = 7321
val seventyTwo = 72


This is really the solution?

**Comment by Primetalk** [comment]
Try giving meaningful names to the constants.
