### ISSUE TITLE
Bug in ScalaStyle parser

### ISSUE THREAD

**Issue by Primetalk** [cotiviti/cotiviti-develtools-config#14]
There is [a known bug in ScalaStyle](https://github.com/scalastyle/scalastyle/issues/191). It happens in `dvaar` project:

     [INFO] --- scalastyle-maven-plugin:0.8.0:check (default) @ dvaar ---
     error file=/_/dvaar/src/main/scala/io/cotiviti/dvaar/AbstractMain.scala message=Expected token SEMI but got Token(IMPORT,import,2242,import)

I suspect that this is due to `http4s` syntax that the parser cannot deal with. That's why we have to [disable failure](https://github.com/cotiviti/cotiviti-develtools-config/wiki/Disable-ScalaStyle-failure-on-validation) on these errors in dvaar.

**Comment by coacoas** [comment]
@Primetalk Is it just the one location in `AbstractMain`?  Does the workaround mentioned in that bug report not work?

**Comment by Primetalk** [comment]
@coacoas I wasn't able to find the exact place. I suspect that it's in pattern matching using `http4s` syntax:

      case GET -> Root / "ping" =>

But I may be wrong.

**Comment by coacoas** [comment]
It looks like the root problem with the parser is the following: 
```scala
import org.http4s.dsl._
import org.http4s.dsl.Root
import org.http4s.dsl.GET
import org.http4s.dsl.Ok
import org.http4s.dsl.POST
```
Note the `_` import followed by a bunch of imports from the same package.  Removing the extra imports allowed the parser to get past this error. 

The same thing occurred in `CotivitiServiceBusyPortSpec.scala`.  Again, leaving just the `_` import allowed the parse to continue.

**Comment by Primetalk** [comment]
@coacoas Thanks!

**Comment by Primetalk** [comment]
With wildcard import it works. However, it then issues a warning. On it. So I turned off the failure on warnings.

**Comment by coacoas** [comment]
Could you not add `// scalastyle:ignore` on that line to get past it?  Disabling failure on warnings is kind of a broadsword vs scalpel solution.

**Comment by coacoas** [comment]
@Primetalk - I tried:
```scala
import org.http4s.dsl._ // scalastyle:ignore Justification: https://github.com/scalastyle/scalastyle/issues/191
```
And that worked fine. Interestingly, it does have to be the underscore import - the specific imports fail.

**Comment by coacoas** [comment]
@Primetalk - Even better!  It works with the following imports: 
```scala
import org.http4s.dsl.`->`
import org.http4s.dsl./
import org.http4s.dsl.Root
import org.http4s.dsl.GET
import org.http4s.dsl.Ok
import org.http4s.dsl.POST
```

**Comment by Primetalk** [comment]
@coacoas 
You've spot it! I think this should be documented somewhere in wiki.

**Comment by isomarcte** [comment]
I actually suspect this is fixed by this commit https://github.com/scala-ide/scalariform/commit/0154cea5aee8a0487c22f7054933e3088e95fb57

...but I don't think they've done a release with that yet...even though it was committed almost a year ago.

**Comment by mykelalvis** [comment]
So what's the resolution for this @Primetalk and @coacoas ?  Anything?

**Comment by coacoas** [comment]
I don't see any need for us to track bugs in other people's code, so I think we should close this. @Primetalk?

**Comment by Primetalk** [comment]
👍
