### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by mykelalvis** [cotiviti/cotiviti-develtools-config#15]
This project doesn't build and the history appears...odd
It's currently set to build 2.0.1-SNAPSHOT although 2.0.1 has apparently been released?

During a release run, I moved it all to 2.1.0-SNAPSHOT.  It still doesn't build, but David (or someone) is working on the scalastyle issues.  

The branch I was working with is [here](https://github.com/cotiviti/cotiviti-develtools-config/tree/feature/unmess_release_version)

**Comment by isomarcte** [comment]
@mykelalvis I do not get any build issues locally, see the attached log. Can you be more specific about the errors you are seeing.

The reason for the discrepancy in the versions numbers is that it appears the PR to merge `master` -> `develop` after the 2.0.1 release was never done. I have created said PR and assigned it to you, https://github.com/cotiviti/cotiviti-develtools-config/pull/16 .

[build.log](https://github.com/cotiviti/cotiviti-develtools-config/files/1368695/build.log)
